### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by rverbee** [weifund/weifund-dapp-basic#1]
When going to https://weifund-basic.surge.sh/ and before selecting a "locale" the text all over the place is strange and not properly formatted. Once I select English it seems to update and be fixed.

**Comment by SilentCicero** [comment]
Yes, I only have a polyfill with some weird differences right now. We dont have translations up. The weirdness is on purpose to show me it's working. This will be addressed when full translations are provided in JSON format.

**Comment by SilentCicero** [comment]
This feature will not be needed at this time, so I'm closing this issue for now.
