### ISSUE TITLE
Suggestion to make error message clearer

### ISSUE THREAD

**Issue by zachyam** [weifund/weifund-dapp-basic#14]
Using metmask chrome extension:

when users click Start Campaign, and when the metamask extension opens, clicking 'reject' gives this error message. 

suggestion to make error message clearer 

https://drive.google.com/a/consensys.net/file/d/0Bz4_k1S4sTQNQ2VfeEVPTDBwUU0/view?usp=sharing

**Comment by SilentCicero** [comment]
Start campaign flow has been removed.
