### ISSUE TITLE
Loading bar to indicate progress of campaign creation?

### ISSUE THREAD

**Issue by zachyam** [weifund/weifund-dapp-basic#15]
From a UI perspective, it might make sense to have an animation / loading bar to indicate to users that their campaign is being created.

https://drive.google.com/a/consensys.net/file/d/0Bz4_k1S4sTQNRVV4MHMtRDRWTWc/view?usp=sharing

**Comment by SilentCicero** [comment]
Yes, this will be added when Campaign Creation flow is added.
