### ISSUE TITLE
Contribution methods in projects

### ISSUE THREAD

**Issue by zachyam** [weifund/weifund-dapp-basic#17]
In a project, when user clicks Back This Project -> Select Contribution Method -> Bitcoin -> via ShapeShift to your Ether address, nothing happens / appears.

This also happens for Other cryptocurrencies -> via ShapeShift to your Ether address

Additionally, both these 2 pages (selecting Bitcoin or Other cryptocurrencies) yield the same result / layout

**Comment by SilentCicero** [comment]
I added ShapeShift link in latest commit.

**Comment by SilentCicero** [comment]
fixed in commit: https://github.com/weifund/weifund-dapp-basic/commit/5f698b622d15da05b872e4553881199a3865e1d7
