### ISSUE TITLE
Validating contribution page

### ISSUE THREAD

**Issue by zachyam** [weifund/weifund-dapp-basic#18]
1. In the contribution form, setting contribution amount to 0 ETH should not allow users to proceed.
2. Users should not be able to contribute without checking the disclaimer notice.
3. Fix css issue: https://drive.google.com/a/consensys.net/file/d/0Bz4_k1S4sTQNaENuU3BPN0oxRUU/view?usp=sharing
4. As pointed out in previous issue, would be good to have an animation / loading bar to indicate to users when contribution has completed

**Comment by SilentCicero** [comment]
Fixed in latest commit. Red highlighting and re-focus.
