### ISSUE TITLE
Standard Campaign - QR Code

### ISSUE THREAD

**Issue by zachyam** [weifund/weifund-dapp-basic#19]
QR code matches the address (when I scan it on Jaxx and compare them). However, when I copy the address and try to send it ether via metamask, an error occurs 

https://drive.google.com/drive/u/1/folders/0B-YFO7z4WHRcYjVOaXB6V1J2V3c

**Comment by SilentCicero** [comment]
Seems to scan fine for me, fixed QR code address in QR view on campaign.

**Comment by SilentCicero** [comment]
fixed in latest commit: https://github.com/weifund/weifund-dapp-basic/commit/5f698b622d15da05b872e4553881199a3865e1d7
