### ISSUE TITLE
Ended Campaigns

### ISSUE THREAD

**Issue by rverbee** [weifund/weifund-dapp-basic#2]
Campaigns which have ended are being shown incorrectly in both the "View Campaigns" and "Campaign Details" views. 

https://drive.google.com/open?id=0B-YFO7z4WHRcR0RpbmcxUWZEU1U

https://drive.google.com/open?id=0B-YFO7z4WHRcLVlxaVBwYm9XODQ

**Comment by SilentCicero** [comment]
Ah, good find. Yes, that is the inverse days being calculated. I need to fix inverse days, and render it as zero. Good catch.

**Comment by SilentCicero** [comment]
fixed in commit: https://github.com/weifund/weifund-dapp-basic/commit/c9781ae6a1d44941a882cfbc85beb2bbb4e48889
