### ISSUE TITLE
Suggestions for WeiFund client

### ISSUE THREAD

**Issue by HowardWei** [weifund/weifund-dapp-basic#20]
1. Indicate which campaigns are operational and which campaigns are not. This is just useful from a usability perspective.
2. When contributing to a campaign through the interface, information about the current state of the campaign should be included on the page where you select the contribution amount. This helps to remind the user of the scope of the campaign when deciding the amount of ether they wish to contribute.

**Comment by SilentCicero** [comment]
Good idea, I'll list that in the main interface.
