### ISSUE TITLE
Payout to Beneficiary

### ISSUE THREAD

**Issue by rverbee** [weifund/weifund-dapp-basic#22]
This is an enchancement request.

Since it is confusing to many people once a campaign is over to see the payout to Beneficiary button, it should be shown in the campaign details view, or only be shown to the beneficiary. 

Although I realise that it doesn't actually matter, I think given the confusion it would cause we should change this before production launch. 

It could also just be a text link with some text describing how the button works, etc.

**Comment by SilentCicero** [comment]
This will be removed until a later client.
