### ISSUE TITLE
Etherscan link on Contract details view missing

### ISSUE THREAD

**Issue by rverbee** [weifund/weifund-dapp-basic#23]
<img width="469" alt="screen shot 2016-10-03 at 2 43 15 pm" src="https://cloud.githubusercontent.com/assets/1045979/19049330/fc39f4d2-8977-11e6-940d-d6c26ef151e2.png">

**Comment by SilentCicero** [comment]
Fixed in latest commit.

**Comment by SilentCicero** [comment]
fixed in commit: https://github.com/weifund/weifund-dapp-basic/commit/5f698b622d15da05b872e4553881199a3865e1d7
