### ISSUE TITLE
Feature - Mainnet Notice [prompt notice on mainnet or testnet awareness]

### ISSUE THREAD

**Issue by rverbee** [weifund/weifund-dapp-basic#24]
As a user coming to WeiFund on Mainnet, I want to see information about how WeiFund is only on the testnet now, plus maybe some instructions on how to switch nets since I may not be so savvy...

**Comment by SilentCicero** [comment]
This feature will be added, with a pop-up box.

**Comment by SilentCicero** [comment]
added in latest commit: https://github.com/weifund/weifund-dapp-basic/commit/5f698b622d15da05b872e4553881199a3865e1d7
