### ISSUE TITLE
Post Bug Bounty: Lightwallet integration

### ISSUE THREAD

**Issue by gaton2** [weifund/weifund-dapp-basic#29]

**Comment by rverbee** [comment]
Left to do:
Contribution Flow UI that uses the mouse entropy
(update with input from user stories)

**Comment by rverbee** [comment]
Nick almost finished deploying to Ropsten.
Will update dapp-basic once online. 
Infura issued resolved.

**Comment by rverbee** [comment]
1. Get dApp Client ready and instantiating what Nick has for the contribution flow right now. 
2.Outline the remaining steps in a mockup for other relevant description.
3.Implement final steps.
