### ISSUE TITLE
It asks me if I want to leave but I haven't made any changes

### ISSUE THREAD

**Issue by rverbee** [weifund/weifund-dapp-basic#3]
https://drive.google.com/open?id=0B-YFO7z4WHRcYmd3MUFqRTFLRmM

**Comment by SilentCicero** [comment]
Yes, this is platform wide. I think I will only promt this on contribution/refund/payout flows. Good point.

**Comment by SilentCicero** [comment]
fixed in commit: https://github.com/weifund/weifund-dapp-basic/commit/c9781ae6a1d44941a882cfbc85beb2bbb4e48889
