### ISSUE TITLE
Campaign End Date

### ISSUE THREAD

**Issue by rverbee** [weifund/weifund-dapp-basic#5]
On campaign creation, the campaign date slider is weird. Seems like a strange user experience to enter decimal places for days. What is 1.65 days anyways?

End Date seems to suggest that you would enter a "date" on a calendar. Otherwise we should ask for the length of the campaign in the number of days. 

https://drive.google.com/open?id=0B-YFO7z4WHRcS2I0enNBRWxma00

**Comment by rverbee** [comment]
These are just my thoughts. Interested to hear yours. Again, I'm not super concerned about the start campaign flow. As far as I was concerned we should just be launching the bug bounty program on a couple of campaigns in preproduction and one on main net for production with some ether in it. The start campaign feature might be out of scope for the launch.

**Comment by SilentCicero** [comment]
agreed, will fix. a calendar selector is far more appropriate.

**Comment by rverbee** [comment]
Although the start campaign flow feels really good .... feels really really good.

But you know... etc...

**Comment by SilentCicero** [comment]
fixed in: https://github.com/weifund/weifund-dapp-basic/commit/c9781ae6a1d44941a882cfbc85beb2bbb4e48889
