### ISSUE TITLE
Two Transaction Pop Ups - No explanation

### ISSUE THREAD

**Issue by rverbee** [weifund/weifund-dapp-basic#6]
As a user who is not familiar with why there are two trans to set up a campaign, we should be providing the user more explicit reasons for them. 

https://drive.google.com/open?id=0B-YFO7z4WHRcWnRoVTZrUG9SREk

**Comment by SilentCicero** [comment]
I did, but obviously not enough. If you read the print. We will provide more explicit information.

**Comment by SilentCicero** [comment]
Most likely as a pop-up.

**Comment by SilentCicero** [comment]
fixed in commit: https://github.com/weifund/weifund-dapp-basic/commit/c9781ae6a1d44941a882cfbc85beb2bbb4e48889
