### ISSUE TITLE
The Technical Details Seem to be hardcoded at the moment

### ISSUE THREAD

**Issue by rverbee** [weifund/weifund-dapp-basic#8]
https://drive.google.com/open?id=0B-YFO7z4WHRcVndfNnhuSGp0WWM

https://drive.google.com/open?id=0B-YFO7z4WHRcVGtqUU1RTV95bFE

**Comment by SilentCicero** [comment]
@rverbee yes, those have not been activated. Will do.

**Comment by SilentCicero** [comment]
@rverbee these details are now active.
